# Form implementation generated from reading ui file 'sprawdzian.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setEnabled(True)
        Dialog.resize(187, 217)
        self.internista = QtWidgets.QRadioButton(parent=Dialog)
        self.internista.setGeometry(QtCore.QRect(20, 40, 95, 20))
        self.internista.setObjectName("internista")
        self.pediatra = QtWidgets.QRadioButton(parent=Dialog)
        self.pediatra.setGeometry(QtCore.QRect(20, 60, 95, 20))
        self.pediatra.setObjectName("pediatra")
        self.dermatolog = QtWidgets.QRadioButton(parent=Dialog)
        self.dermatolog.setGeometry(QtCore.QRect(20, 80, 95, 20))
        self.dermatolog.setObjectName("dermatolog")
        self.checkBox = QtWidgets.QCheckBox(parent=Dialog)
        self.checkBox.setGeometry(QtCore.QRect(20, 110, 121, 20))
        self.checkBox.setChecked(True)
        self.checkBox.setTristate(False)
        self.checkBox.setObjectName("checkBox")
        self.pushButton = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton.setGeometry(QtCore.QRect(30, 140, 93, 28))
        self.pushButton.setCheckable(True)
        self.pushButton.setDefault(False)
        self.pushButton.setObjectName("pushButton")
        self.lekarz_result = QtWidgets.QLabel(parent=Dialog)
        self.lekarz_result.setGeometry(QtCore.QRect(10, 180, 181, 41))
        self.lekarz_result.setText("")
        self.lekarz_result.setObjectName("lekarz_result")
        self.cena = QtWidgets.QLabel(parent=Dialog)
        self.cena.setGeometry(QtCore.QRect(250, 210, 101, 31))
        self.cena.setText("")
        self.cena.setObjectName("cena")
        self.lineEdit = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(20, 10, 113, 22))
        self.lineEdit.setObjectName("lineEdit")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.internista.setText(_translate("Dialog", "internista"))
        self.pediatra.setText(_translate("Dialog", "pediatra"))
        self.dermatolog.setText(_translate("Dialog", "dermatolog"))
        self.checkBox.setText(_translate("Dialog", "wizyta prywatna"))
        self.pushButton.setText(_translate("Dialog", "rezerwuj"))
        self.lineEdit.setText(_translate("Dialog", "imie"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
